remote_theme: pmarsceill/just-the-docs

plugins:
  - jemoji
  - jekyll-seo-tag

baseurl: "/PhpStormNinja" # subpath of site

aux_links:
  "PhpStorm Ninja on GitHub":
    - "//github.com/ChrisGalliano/PhpStormNinja"